apiVersion: v1
kind: Pod
metadata:
  name: f-nginx-pod
spec:
  containers:
  - name: f-nginx-container
    image: nginx
    env: 
      - name: SERVER_URL_ENV
        valueFrom:
          configMapKeyRef:
            name: f-config
            key: SERVER_URL
