/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package productapp;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    Product pro = new Product();
    pro.name();
    pro.description();
    pro.price();
    }

}

class Product {
    public void name(){
        System.out.println("Productapp");
    }
    public void description(){
        System.out.println("This is the sample description of Productapp");
    }
    public void price(){
        System.out.println("The price is 5$");
    }
}

