kind: PersistentVolume
apiVersion: v1
metadata:
  name: f-pv
  labels: 
  type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/fresco"
  storageClassName: manual
